[package]
name = "orientation_correction"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = { version = "0.53.1", features =["clang-runtime"]}
tesseract = "0.9.0"
mecab = "*"
regex = "1.4.2"